name: Build

on:
  push:
    branches:
      - 'releases/**'

jobs:
  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.17.2]

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm i --legacy-peer-deps

      - name: Set and export environment variable
        uses: myci-actions/export-env-var@1
        with:
          name: GITHUB_TOKEN
          value: ${{ secrets.TOKEN }}

      - name: build:mac
        run: npm run pkg:mac

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Ditto++_Setup_MacOS
          path: out/*.dmg

  build-win:
    needs: build-mac
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.17.2]

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm i --legacy-peer-deps

      - name: Set and export environment variable
        uses: myci-actions/export-env-var@1
        with:
          name: GITHUB_TOKEN
          value: ${{ secrets.TOKEN }}

      - name: build:win
        run: npm run pkg:win

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Ditto++_Setup_Windows
          path: out/*.exe

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: Ditto++_Setup_MacOS

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'out/*.exe, *.dmg'
          token: ${{ secrets.TOKEN }}
