# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
   
    strategy:
      matrix:
        node-version: [14.17.2]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm i --no-optional
  
      - name: build:win
        run: npm run pkg:win
       
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Ditributale files
          path: out/*.exe
